### PR TITLE
Feature/multiple random images

### PR DESCRIPTION
**Pull request by edc0der**
Create new endpoint which retrieves multiple random images of any breed

### CODE REVIEW

**Comment by ElliottLandsborough** [comment]
Thanks! I made a few minor changes but we always welcome new features.

The changes will be on the live site today or tomorrow.

**Comment by ElliottLandsborough** [comment]
Fyi the changes are on live with a maximum $amount of 50

https://dog.ceo/api/breeds/image/random/50

**Comment by jigsawpieces** [comment]
Have updated documentation page with new endpoints: https://dog.ceo/dog-api/documentation/random

**Comment by trishaputhran** [comment]
How do I display the images on a webpage? It doesn't have any parameters.

**Comment by iamraafay** [comment]
How would it know if it's not returning the same image in the subsequent API calls?

**Comment by ElliottLandsborough** [comment]
@trishaputhran here are some examples of how to show an image on a webpage:

Vanilla JS: https://codepen.io/elliottlan/pen/MNEWNx
Jquery: https://codepen.io/elliottlan/pen/KOXKLG

@iamraafay there is no guarantee that it will not return the same image in subsequent api calls.

**Comment by edc0der** [comment]
@wayungi I believe you should contact @ElliottLandsborough to find an answer for your search. 
At the time of this PR I was working on a demo app which needed this feature, as it wasn't implemented, I made a fork, developed it, and made a pull request. 
But the project itself is not mine, and I've not kept up with it since 2018. 
Cheers.

**Comment by pavel-035** [comment]
> не понимаю как можно сделать что бы были все данные. Что-бы фото и данные о собаки были вот пример : https://codepen.io/zvpxghez-the-sans/pen/qBGdZWa

Привет! Не разобралась?

**Comment by pavel-035** [comment]
Если почитать readme.md, то можно обнаружить раздел Beta/Unfinished Endpoints. Стоит обратить внимание, что это не законченные endpoints, в которых возможны изменения. В этом разделе есть endpoints позволяющие получить не только изображение, но и информацию о собаке.

If you read readme.md, you can find the Beta/Unfinished Endpoints section. It is worth noting that these are not finished endpoints, which are subject to change. This section contains endpoints that allow you to get not only an image, but also information about the dog.

**Pull request merged**
